### ISSUE TITLE
Mobx planned support? 

### ISSUE THREAD

**Issue by lishine** [pshrmn/curi#10]

**Comment by pshrmn** [comment]
Hey @LiShine. I plan to add support, but haven't gotten around to it yet. I have only used MobX a tiny bit, so I'll have to re-educate myself on how it works, but I think that it will be quite easy to integrate with Curi. Whether that is a `@curi/mobx` package or just a guide (if a package is overkill) I'm not sure.

It _might_ be as simple as something like this to keep the MobX store in sync:
```js
const router = curi(history, routes);

// initial state
const curiStore = observable({
  router,
  response: null,
  action: null
});

// update store whenever a response is emitted
router.respond((response, action) => {
  curiStore.response = response;
  curiStore.action = action;
});

// render after initial response is emitted, using { once: true }
// since updates to the MobX store should trigger any future
// re-renderes
router.respond(() => {
  ReactDOM.render((
    <CuriBase
      router={curiStore.router}
      response={curiStore.response}
      action={curiStore.action}
      render={renderFunction}
    />
  ), holder);
}, { once: true });
```
The actual solution will probably be different than that, but I think it will be something along those lines. I'll update this issue once I have figured out what works best (or if someone else who is familiar with MobX comes by with a solution, that would be appreciated too).

**Comment by pshrmn** [comment]
Added a `@curi/mobx` package in #12. You can see a simple demo here https://codesandbox.io/s/github/pshrmn/curi/tree/master/examples/react/mobx. I still need to add documentation, but it appears to work well (and was quite simple to implement).
