### ISSUE TITLE
Examples on codesandbox.io broken

### ISSUE THREAD

**Issue by sun2rise** [pshrmn/curi#107]
Every example [this page](https://curi.js.org/examples) is broken.

I like your project very much, other routers feel bloated to me... but it is just a feeling, could you tell me why should I use it instead of `react-router`? (if not now, in the future)

Thanks!

**Comment by pshrmn** [comment]
Ah, shoot. I made some changes to the `@curi/react-dom` API, and the examples with those changes went live when I merged the PR, but I haven't published the changes yet. I just published the updated packages, so everything should be working correctly no. Sorry about that!

As far as reasons to use Curi go, I think that it has the best API of any router I have used (or looked into). A few of my favorite things:

1. Named routes allow you to specify which route you want to navigate to. You don't have to concatenate strings yourself and they negate the need for relative links.

```jsx
<Link to="User" params={{ id: 'sun2rise' }}>sun2rise</Link>
```

2. Curi's "response" pattern makes it easy control what is rendered. You use a route's `response()` property to return data that is relevant to what you want to render, most specifically, which component(s). You can even attach multiple components to easily put together complex UIs.

```jsx
const routes = [
  {
    name: "Home",
    path: "",
    response() {
      return {
        body: { Main: Home, Menu: HomeMenu }
      };
    }
  }
];

<Router>
  ({ response }) => {
    const { Main, Menu } = response.body;
    return (
      <React.Fragment>
        <Menu />
        <Main />
      </React.Fragment>
    );
  }
</Router>
```

3. Other routers, have this concept with nested routes where you are rendering content for not only the route that matches, but also ancestors that match. I really dislike this pattern; I believe that the only content that should be rendered for a location is the route that matches the location. If an ancestor and descendant route should share some content, you can do that, but it isn't forced on you.

4. I am also quite happy with Curi's documentation and I think that the examples (now that they are fixed, sorry about that, again!) do a good job showcasing what can be done.

If you have any questions, I am happy to give my insight. One of the toughest parts about writing OSS by myself is that I might completely overlook something that is obvious to other people, so getting any feedback is really helpful for me.

**Comment by sun2rise** [comment]
I agree with 4/4 points.
Thanks for your work, thanks for the documentation, you deserve my :star:
See you around
