### ISSUE TITLE
How to render different components while keeping the header and drawer constant?

### ISSUE THREAD

**Issue by abhisheksoni27** [pshrmn/curi#118]
So, I have an App which has a header and a drawer. Now, apart from that, I have a `Content` component that renders some thing on the page. How can I use curi to render different components inside that `Content` based on what was clicked in Drawer?

This is how my App looks like: 

```jsx
ReactDOM.render((
    <MuiThemeProvider theme={theme}>
      <Router>
        {
            ({ response }) => {
              const { body:Body } = response;
              return (
              <Body response={response} />
              );
            }
        }
      </Router>
    </MuiThemeProvider>
  ), document.getElementById('root'));
```

And I have somed direct routes in `routes.js`. The problem is: If I add a children route to, let's say the Home route, the entire page only displays the components I write inside that Route. (i.e., the Header and the drawer obviously disappear.)

This is how I'd do it with React-Router:

```jsx
<HashRouter>
  <Switch>
    <Route
      exact
      path={match.path}
      component={Messages}
    />
    <Route
      exact
      path={`${match.path}/:message`}
      component={Message}
    />
  </Switch>
</HashRouter>
```

**Comment by pshrmn** [comment]
Hey @abhisheksoni27. Do you want the `Header` and `Drawer` to be the same for every single route and only vary the `Content` (or `Body` in this case)? To do that, you can render those in the render-invoked function. I think of that function as the root of the app's layout.

```jsx
ReactDOM.render((
    <MuiThemeProvider theme={theme}>
      <Router>
        {
            ({ response }) => {
              const { body:Body } = response;
              return (
                <React.Fragment>
                  <Header />
                  <Drawer />
                  <Body response={response} />
                </React.Fragment>
              );
            }
        }
      </Router>
    </MuiThemeProvider>
  ), document.getElementById('root'));
```
There is a slightly more advanced use case, too, where you can attach multiple components to `response.body`. This is useful if you have multiple sections of the page that vary based on the route. For example, you might have different headers based on the route, in addition to the content. You can see an example of what I am talking about here: https://curi.js.org/examples/react/multi-body/.

**Comment by pshrmn** [comment]
Err, I just re-read your question and realize that I may have misinterpreted your question, but I think that my example code should still help. Please let me know if I'm completely off from what you are trying to do.

**Comment by abhisheksoni27** [comment]
Actually, your explanation was exactly what was required to answer my question. That worked like a charm Thank you so much, and great library! :+1:
