### ISSUE TITLE
Twitch example is... well, twitching :D

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#14]
https://curi.js.org/examples/full/twitch/

**Comment by pshrmn** [comment]
Huh, that is weird. I haven't done anything with it lately and it works locally, so I want to say that it is something that CodeSandbox has changed. I'll take a look at what could be causing the issue, but nothing is immediately standing out.

**Comment by loganpowell** [comment]
Yeah, it worked for me the first time I checked it out... now says "Glitch!" real big and red at the top while if flickers...

**Comment by pshrmn** [comment]
The demo is fixed now. CodeSandbox runs tests now (maybe not officially yet) and there was an issue with that that was causing the reloads.
