### ISSUE TITLE
Parent Resolve Correlation to Child Route

### ISSUE THREAD

**Issue by mparker11** [pshrmn/curi#142]
Just a question: Do children routes get the `resolve` value from the parent?

**Comment by pshrmn** [comment]
No, `resolve` is only the results of the matched route's `resolve` functions. If multiple routes want the same functionality, I would split it out to its own function.

```js
function resolveSomething() {
  return Promise.resolve("something");
};

export default prepareRoutes([
  {
    name: "Parent",
    path: "p/:pID",
    resolve: {
      something: resolveSomething
    },
    children: [
      {
        name: "Child",
        path: ":cID",
        resolve: {
          something: resolveSomething
        }
      }
    ]
  }
]);
```
Do you have a use case where that doesn't work well?

**Comment by mparker11** [comment]
I figured that was the case. My only concern was making the same API call multiple times even though the parent already got the information. I've solved it already saving info in the app, but I was just wondering if you had implemented something as well. Thanks for the quick responses as usual.

**Comment by pshrmn** [comment]
Yes, caching function results is probably the best bet. The [`once`](https://curi.js.org/packages/@curi/helpers/#once) function exported by the `@curi/helpers` package provides very basic caching. There are also some caching/memoization packages that provide more robust solutions. (or you can always roll your own solution).
