### ISSUE TITLE
Offscreen positioning possibly bad for RTL languages

### ISSUE THREAD

**Issue by danielnixon** [pshrmn/curi#193]
I haven't verified this but I suspect the [technique you're using](https://github.com/pshrmn/curi/blob/master/packages/side-effects/side-effect-aria-live/src/index.ts#L9) to make your aria-live announcer visually hidden (negative positioning) won't work for right-to-left languages.

See:
* https://a11yproject.com/posts/how-to-hide-content/
* https://hugogiraudel.com/2016/10/13/css-hide-and-seek/
* https://getbootstrap.com/docs/4.3/getting-started/accessibility/#visually-hidden-content
* https://github.com/twbs/bootstrap/blob/ff29c1224c20b8fcf2d1e7c28426470f1dc3e40d/scss/mixins/_screen-reader.scss#L6

**Comment by danielnixon** [comment]
Oh and https://snook.ca/archives/html_and_css/hiding-content-for-accessibility

**Comment by pshrmn** [comment]
Thanks! A release with better styling should be out relatively soon.
