### ISSUE TITLE
'process' is not defined

### ISSUE THREAD

**Issue by sarathkcm** [pshrmn/curi#217]
I am just getting started with Svelte and Curi. I setup everything as per the guides, but while running the app, I am getting the following error on borwser.

![image](https://user-images.githubusercontent.com/14143311/58748895-9620b000-849c-11e9-93ba-ac09dd821288.png)

I worked around it by adding a `window.process = window.process || { env: {} };` in my _routes.js_, but it looked like a bug and thought I should report it.

**Comment by pshrmn** [comment]
How are you bundling your application? Typically bundlers (Webpack, Rollup, etc.) are configured to replace `process.env.NODE_ENV` while bundling, which allows applications to have errors/warnings in dev that get removed in production.

**Comment by pshrmn** [comment]
Also, I appreciated any feedback that you have, especially with `@curi/svelte`. I am mostly satisfied with the API (some internal stuff isn't ideal), but I want to give it a little more time before I release `@curi/svelte` v2.

**Comment by sarathkcm** [comment]
I read about `selvete` this morning, and `@curi/svelte` about 2 hours ago. :) . So I do not have enough experience with the library to provide any feedback yet. But I did make the decision to use it because I thought the API was nice and easy to use. All of the other solutions I checked out looked cumbersome or lacked a guide on how to use with svelte. kudos to you for that.

**Comment by sarathkcm** [comment]
> How are you bundling your application? Typically bundlers (Webpack, Rollup, etc.)

I am using the default svelte template, which uses rollup. Here is a zip of the sources files that can reproduce the issue, if you need it. I am running `npm run dev` to run the application.

[process-undefined.zip](https://github.com/pshrmn/curi/files/3243846/process-undefined.zip)

Its also possible that I have done something wrong in the my code.

**Comment by sarathkcm** [comment]
> Typically bundlers (Webpack, Rollup, etc.) are configured to replace `process.env.NODE_ENV` while bundling

After reading this I searched if Rollup supports this, and it apparantly doesn't do that. I will need to use a plugin to replace all `process.env.NODE_ENV`.

I think this issue can be closed.

https://github.com/rollup/rollup/issues/487

**Comment by pshrmn** [comment]
Oh, yes, with Rollup you need to use the replace plugin. The one thing to keep in mind is that you replace with `"development"` while in dev and `"production"` for your actual build. I'll close this issue, but if you have any other issues/questions, feel free to ask.
