### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by KleinMaximus** [pshrmn/curi#218]
```
<script>
  import Router from '@curi/svelte/components/Router.svelte';
  // ...
</script>
```

Error:
```
/home/kleinmaximus/Projects/KleinMaximus/razzle-svelte/node_modules/@curi/svelte/components/Router.svelte:1
<script>
^

SyntaxError: Unexpected token <
```

I think that the components need automatically compile before publishing (or during the installation of the package).
Then there will be no dependency on a particular developer's environment.
At least that's what Vue does.
In addition, the components can be imported via `import { Router } from '@curi/svelte';` if include them to index file.

P.S.: Sorry for my English ;)

**Comment by KleinMaximus** [comment]
For example - https://github.com/lokyoung/vuejs-paginate/blob/master/src/index.js
In ./dist folder we get a already compiled in javascript component without the need for any additional configuration or some actions. Simple `import { AsyncLink, Link, Navigating, Router } from '@curi/svelte'`.

**Comment by pshrmn** [comment]
Publishing Svelte packages is sort of a weird place where I'm not sure what the best practices are. I think that it is better to publish raw component files because if I pre-compiled them, you would be stuck with my compile options (es/cjs `format`, `dev` for warnings, etc.).

How are you building your application?

**Comment by KleinMaximus** [comment]
> How are you building your application?

webpack

**Comment by KleinMaximus** [comment]
webpack rule
```
{
  test: /\.svelte$/,
  use: {
    loader: 'svelte-loader',
    options: {
      dev,
      emitCss: true,
      generate: target === 'node' ? 'ssr' : 'dom',
      hydratable: true,
    },
  },
}
```

**Comment by pshrmn** [comment]
Hmm, I feel like the `@curi/svelte` components should be compiled by that configuration. I use something similar in the Svelte examples: https://github.com/pshrmn/curi/blob/bbcc5d8ba850b8dde8e72e037e7d46371cf4f8dd/examples/configs/webpack/webpack.svelte.config.js
