### ISSUE TITLE
.html > .svelte

### ISSUE THREAD

**Issue by KleinMaximus** [pshrmn/curi#219]
https://github.com/pshrmn/curi/blob/bbcc5d8ba850b8dde8e72e037e7d46371cf4f8dd/packages/svelte/rollup.config.js#L13

I'm not sure if this is a mistake, but I think need chang from `include: "src/**/*.html"` to `include: "src/**/*.svelte"`.

**Comment by pshrmn** [comment]
This is an artifact from an early build. It isn't doing anything right now, but I can remove it.
