### ISSUE TITLE
[Tutorial] Would be helpful to add file/folder location to instructions

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#22]
For example in [Step 03](https://curi.js.org/tutorial/03-hickory)

```js
import Browser from '@hickory/browser';
const history = Browser();
```
would be nice if:
```js
// src/index.js
import Browser from '@hickory/browser';
const history = Browser();
```

**Comment by loganpowell** [comment]
I can create a PR if you'd like?

**Comment by pshrmn** [comment]
A PR would be great.

**Comment by loganpowell** [comment]
Just a note: only the first four tuts seemed to benefit from additional context. You have included context in the remainder of the tuts!
