### ISSUE TITLE
Navigation not working if using svelte beyond v3.6.4

### ISSUE THREAD

**Issue by si3nloong** [pshrmn/curi#224]
<img width="552" alt="Screenshot 2019-07-14 at 12 51 48 AM" src="https://user-images.githubusercontent.com/28108597/61174387-d877f980-a5d1-11e9-973b-59fb99d63972.png">

**Comment by pshrmn** [comment]
Can you show the code where you render the `Link`? Also, did this work with Svelte <3.6.4?

**Comment by pshrmn** [comment]
There error that you are referring to is [this line](https://github.com/pshrmn/curi/blob/37bb29b42d530b7484fa8149f9d2d9207362efee/packages/svelte/components/Link.svelte#L38), which makes me think that your router context isn't correct. I would recommend taking a look at some of the examples ([the basic example is a good reference](https://codesandbox.io/s/github/pshrmn/curi/tree/master/examples/svelte/basic)) to make sure that you have the router setup correctly.

**Comment by si3nloong** [comment]
Yes, i have the same setup, it working on svelte v3.6.4, but not after, try to use svelte v3.6.5 in https://codesandbox.io/s/curi-examplebasic-svelte-mvql4, it will not working as expected

**Comment by pshrmn** [comment]
Are you getting the same issues locally? I ran the basic example locally with Svelte `3.6.5` and it worked.

**Comment by si3nloong** [comment]
I figure out there would be other component issue. Nevertheless, it reproduce another new error.
<img width="957" alt="Screenshot 2019-07-14 at 12 10 51 PM" src="https://user-images.githubusercontent.com/28108597/61179231-3c7dda80-a631-11e9-9ae4-fbd88dd308e7.png">

I think it probably related to this issue.
https://github.com/sveltejs/svelte/issues/3165

**Comment by pshrmn** [comment]
Are you implementing some sort of transition in your application? I don't think that that error is coming from `@curi/svelte`. Also, that issue implies that the error is gone in `3.6.7`; have you tested that version?
