### ISSUE TITLE
How do I change route programmatically 

### ISSUE THREAD

**Issue by timsayshey** [pshrmn/curi#233]
Might seem obvious but after reading all the docs I can't find a way to change the route via Javascript. 

Help appreciated :)

**Comment by timsayshey** [comment]
I found the navigate method but it doesn't look like you can pass a `route` name. You have to pass the `url` which is unfortunate since I will only have the route name and params available. Is there a way to work with these?

**Comment by pshrmn** [comment]
You can use [`router.url`](https://curi.js.org/v2/@curi/router/#url) to generate a url string.
