### ISSUE TITLE
Typescript Type Error for <Link>

### ISSUE THREAD

**Issue by martavis** [pshrmn/curi#237]
Hi, I hope all is well.

Still using Curi and still loving it. I just ran into an error from Typescript while trying to using the <Link> component. The issue is <Link> is asking for props `url` and `canNavigate` and I have always only used `name` in regular JSX. Is there something different I need to do when using <Link> in Typescript? I have a screenshot for reference. Thanks!

![image](https://user-images.githubusercontent.com/47053705/78343607-f5819d80-754f-11ea-89c7-33c2e00c3812.png)

**Comment by pshrmn** [comment]
Oh, sorry! Will take a look this evening and hopefully push a fix.

**Comment by pshrmn** [comment]
I just published `@curi/react-dom` `v2.0.2`.

**Comment by martavis** [comment]
Awesome. Thank you very much!
