### ISSUE TITLE
webiste on different folder structure

### ISSUE THREAD

**Issue by wighawag** [pshrmn/curi#244]
I would like to use curi and successfuly managed to setup the router for my webapp
But I am hitting an issue:
I would like my webapp to be hosted on various folder structure without requiring change in code.

It should work on `<domain>/` but also on `<domain>/folder/` where both are the index page.
An `about` page would be `<domain>/about` and `<domain>/folder/about/` respectively  

Since the path parameter has the dual role of regex and path to use, curi does not seem to support `<domain>/folder/` case

when I added 

```
pathOptions: {
      match: {
        start: false,
      },
    },
```

the matching worked (but I add to put "Home" last (because a slash with `start: false` would match all rout ending with a slash)

But then navigation do not remember the folder and thus navigate back to the root.

I guess curi need to be updated to support that or I am missing something ?

**Comment by wighawag** [comment]
Maybe curi could have an option to regex out the basepath and prepend it automatically

**Comment by pshrmn** [comment]
Supporting having the same routes on both the root and in nested folders is a bit of a tricky case.

My first instance is that you could copy the routes.

```ts
const baseRoutes = [
 { name: 'One', path: 'one' },
 { name: 'Two', path: 'two' },
  // ...
];

const routes = prepareRoutes([
  { name: 'Folder', path: 'folder', children: [...baseRoutes] },
  ...baseRoutes
]);
```

However, that would fail the uniqueness of route names, so you should need to have something that walks through the routes and changes their names.

```ts
function asNestedRoutes(prefix, routes) {
  const prefixedRoutes = [];
  for (route of routes) {
    const copy = {
      ...route,
      name: `${prefix} ${route.name}`
    }
    if (route.children && route.children.length) {
      copy.children = asNestedRoutes(prefix, route.children);
    }
    prefixedRoutes.push(copy);
  }
  return prefixedRoutes;
}

const routes = prepareRoutes([
  { name: 'Folder', path: 'folder', children: asNestedRoutes('Folder', baseRoutes) },
  ...baseRoutes
]);
```
I haven't tested that, but in theory it should work.

What is your use case for wanting to have all of the routes also work as nested? Is this for international versions?

**Comment by wighawag** [comment]
Actually my use case is even more constraining that what I described in my first comment.

I have a website hosted on [ipfs](https://ipfs.io) and I want my users to be able to access it via domain name url like https://wighawag.eth.link
But I also want them to be able to use secure ipfs urls like 
https://cloudflare-ipfs.com/ipfs/QmNVTWGZ4qoW4DwiTze3icNJKhKBArR4HrCR1sapAFaPYg/
(which link to the same content but ensure users that the content did not change since last time,)

or potentially through ipns url like : https://cloudflare-ipfs.com/ipns/wighawag.eth.link/

And all these url need to be working at the same time from same hosted data.

Since the ipfs hash is not known before publishing, I have to rely on some regex to extract the basepath at load time.

The simplest regex is the ".*" regex that will match any basepath and works in the ipfs case since all the route need to exists and be listed. And so the basepath can be detected at load time

I started to work on a PR for curi that would allow to support that. 

Obviously with ipfs websites, the parameters extraction (via `path-to-regex`) is not possible but curi has many nice feature that I would like to rely on on my ipfs website.

So having curi support this ipfs website would be great.

**Comment by pshrmn** [comment]
Oh, I think that there is actually a simpler solution for that, then. You can configure a [`base`](https://github.com/pshrmn/hickory/blob/master/docs/api/createBase.md) for your history object.

```ts
import { browser, createBase } from '@hickory/browser';
import { createRouter } from '@curi/router';

const router = createRouter(browser, routes, {
  history: { base: createBase('...') }
});
```
the trick will be to determine what the base is. I imagine that you would inspect the current URL and if the domain is `cloudflare-ipfs.com` you would check for `ipfs`/`ipns` to figure out what the base is.

I realized while looking at this that I forgot to add documentation on passing `history` options when you create the history object. I'll need to get that fixed.

**Comment by wighawag** [comment]
Wow, excelent!, seems to be exactly what I need. Really good job with that router lib. First one I encounter that can support ipfs out of the box :)
