### ISSUE TITLE
Undefined value for optional route parameter

### ISSUE THREAD

**Issue by stalniy** [pshrmn/curi#249]
## Description

When I define optional route parameter `/articles/:id?` and visit `/articles` page, `router.current().response.params` equals `{ id: 'undefined' }`.

## Expected

There should not be `id` field at all or at least it should equal to regular `undefined` value

**Comment by pshrmn** [comment]
Good catch; I was blindly passing the value to the parser function, which by default is `decodeURIComponent`, and that apparently turns `undefined` into `"undefined"`.

I'll omit the property if the value is `undefined`. I was debating which way to prefer, but if you try to create a path and pass an explicitly undefined param, path-to-regexp throws a type error.

**Comment by pshrmn** [comment]
Fixed in `@curi/router@2.1.2`

**Comment by stalniy** [comment]
Cool! Thanks for the quick fix!
