### ISSUE TITLE
`curi.navigation` is marked as required

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#26]
I believe I have everything updated from the tutorial, but I may be doing something wrong. Here's my console error:

```
Warning: Failed context type: The context `curi.navigation` is marked as required in `Curious`, but its value is `undefined`.
    in Curious
    in Unknown (created by CuriBase)
    in main (created by CuriBase)
    in div (created by CuriBase)
    in CuriBase
```

As soon as we clear this up, I'll get on to the highlighting ;)

**Comment by pshrmn** [comment]
The `<Curious>` component expects there to be a `curi.navigation` value on the `context`. That would be set by the `<CuriBase>` component.
```jsx
router.respond((response, navigation) => {
  ReactDOM.render((
    <CuriBase
      router={router}
      response={response}
      navigation={navigation}
      render={render}
    />
  ), holder)
});
```

I previously had just used an `action` string, which I never found very useful so I had made it an optional prop.

I just glanced at the tutorial and I think everything there is correct (the demos work). If I wrote something incorrect, please let me know so I can get that updated.

**Comment by loganpowell** [comment]
Yep, the tutorial is right, but the branch `08-nav-react` has this in the `src/index.js` file:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import curi from '@curi/core';
import Browser from '@hickory/browser';
import { CuriBase } from '@curi/react';

import routes from './routes';
import render from './render';

const history = Browser();
const router = curi(history, routes);

let root = document.getElementById('root');
router.respond(response => {
  ReactDOM.render((
    <CuriBase
      response={response}
      router={router}
      render={render}
    />
  ), root);
});
```

so that was the culprit ;)

**Comment by loganpowell** [comment]
just for clarification, the 08 tut doesn't change that file

**Comment by pshrmn** [comment]
Sorry! Did you clone the repo two days ago? After I had mentioned the tutorial in that other issue, I realized that I hadn't updated some of the branches to use the `navigation` prop. The code is correct now (https://github.com/pshrmn/curi-tutorial/blob/08-nav-react/src/index.js), but if you had grabbed the code before then, it would be missing.

**Comment by loganpowell** [comment]
ah, gotcha. Yep!

**Comment by loganpowell** [comment]
I'm definitely on the ground floor :D

**Comment by loganpowell** [comment]
Ok, so, what's the API for the <Prism dataLine=> prop?

**Comment by pshrmn** [comment]
`data-line` https://github.com/pshrmn/curi/blob/b53c05136358060cb447a9ab68fdf6dc2b889b75/documentation-website/src/client/Tutorials/05-ReactPages.js#L55

**Comment by loganpowell** [comment]
cool. You should make a PR to the React-Prism dude! I'm sure he'd appreciate it :)

**Comment by loganpowell** [comment]
Sorry, real quick question: I don't see any highlight on [that page](https://curi.js.org/tutorial/05-pages-react/). Am I wrong?

**Comment by loganpowell** [comment]
Just in case you're looking for some .css... thought you may like the way the reactjs.org site does this with markdown:

https://github.com/reactjs/reactjs.org/blob/master/content/tutorial/tutorial.md#passing-data-through-props

I think you could just steel their .css. It's too complicated for me to do, else I would. I also think it's pretty clever the way they use markdown... anyway! Onwards.

**Comment by pshrmn** [comment]
You're right, I have to push changes to the `gh-pages` branch for them to be live (you don't have to care about that). I had considered using markdown with the site, but I didn't want to have to maintain two sets of documentation and markdown was too limiting.
