### ISSUE TITLE
[Selling Point] Enables Microfrontends?

### ISSUE THREAD

**Issue by loganpowell** [pshrmn/curi#32]
Just a thought, if you would agree it's a selling-point, couldn't Curi work with the ['microfrontend'](https://medium.com/@tomsoderlund/micro-frontends-a-microservice-approach-to-front-end-web-development-f325ebdadc16) paradigm?

**Comment by pshrmn** [comment]
It's an interesting idea, and I'm sure it _could_ be implemented with Curi, but I don't think I'll focus on it. While using multiple frameworks can a short term solution while transitioning to a new framework, I think that in the long run, trying to duct tape them together will become too unwieldy. I can always revisit this if micro-frontends really do become popular, but I'm already spreading myself a bit thin, so I'll skip this for now.
