### ISSUE TITLE
set.redirect seemingly only redirecting to '' route

### ISSUE THREAD

**Issue by bfillmer** [pshrmn/curi#42]
## `set.redirect` seemingly only redirecting to `''` route

Not sure if I'm implementing something incorrectly, but I have this type of basic structure I am working with:

```javascript

import {Home} from 'view/Screens/Home'
import {Account} from 'view/Screens/Account'

import {login, handleAuthentication, isAuthenticated} from 'auth'

export const routes = [
  {
    name: 'Callback',
    path: 'callback',
    match: {
      every: ({params}) => handleAuthentication(),
      response: ({set}) => {
        console.log('Callback')
        set.body(null)
        set.redirect({name: 'Account'}, null)
      }
    }
  },
  {
    name: 'Login',
    path: 'login',
    match: {
      response: ({set}) => {
        set.body(null)
        login()
      }
    }
  },
  {
    name: 'Account',
    path: 'account',
    match: {
      response: ({set}) => {
        console.log('Account')
        if (!isAuthenticated()) {
          set.body(null)
          set.redirect({name: 'Home', status: 302})
        } else {
          set.body(Account)
        }
      }
    }
  },
  {
    name: 'Home',
    path: '',
    match: {
      response: ({set}) => {
        console.log('Home')
        set.body(Home)
      }
    }
  },
  {
    name: 'route/404',
    path: '(.*)',
    match: {
      response: ({set}) => {
        console.log('404')
        set.body(Home)
      }
    }
  }
]
```

Login is working great, however redirects back _always_ console log `Home`. I've also swapped the redirect on `Account` to redirect to `Login` if you aren't authenticated and that one as well simply loads `Home`. I saw https://github.com/pshrmn/curi/pull/39, any chance the pathname match in there isn't finding my routes for some reason?

**Comment by pshrmn** [comment]
That was my fault; the `set.redirect` changes hadn't been published. I just published, so if you install `@curi/core@1.0.0-beta.27` everything should work as expected (but please let me know if it isn't).

Normally I publish pretty quickly so the docs stay current with what has been published, but maybe I should look into how to structure them so that changes aren't pushed to the site until the related code is published.
