### ISSUE TITLE
Server side in Create React App

### ISSUE THREAD

**Issue by mparker11** [pshrmn/curi#43]
Has anyone done server-side rendering with Curi in Create React App? I'm getting a little lost. Content is showing but the styles and data from the router isn't showing. This is my code, pretty much copied from  https://github.com/pshrmn/curi/blob/2dca9d5b41fd6924d6221dd334710646f1c11ea5/examples/misc/server-rendering/renderer.js.

```
import React from 'react';
import { renderToString } from 'react-dom/server';
import InMemory from '@hickory/in-memory';
import curi from '@curi/core';
import { CuriProvider } from '@curi/react';
import App from '../../src/containers/App';  
import routes from '../../src/routes';

export default function(req, res) {
    const history = InMemory({ locations: [req.url] });
    const router = curi(history, routes);

    router.respond(() => {
        const markup = renderToString(
            <CuriProvider router={ router }>
                {({ response }) => {
                    const { body: Body, params } = response;
                    return (
                        <App>
                            <Body response={ response } />
                        </App>
                    );
                }}
            </CuriProvider>
        );
        res.send(renderFullPage(markup));
    });
}

function renderFullPage(html) {
    return `
        <!DOCTYPE html>
        <html lang="en">
            <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1"> 
            </head>
            <body>
                <noscript>
                    You need to enable JavaScript to run this app.
                </noscript>
                <div id="root">${ html }</div>
                <script type="text/javascript" src="/static/js/bundle.js"></script>]
            </body>
        </html>
    `;
}
```

Any help would be appreciated. Thanks!

**Comment by pshrmn** [comment]
> Content is showing but the styles and data from the router isn't showing.

Can you expand on what styles/data you are referring to? I assume you are styling your components with CSS-in-JS because you don't have a `<link>` to a `.css` file in your `<head>`.

**Comment by mparker11** [comment]
I'm using Sass. So I have the basic markup showing, but no data (rather, props) such as the `router`, `response` and `navigation` from the Curious element.

**Comment by pshrmn** [comment]
Would you be able to upload your code to a repo? It would be easier to help if I could see your routes/where you are using the `<Curious>` component.

Is your SASS compiling to CSS or is Webpack bundling it with your JS (I haven't really used Create React App, so I'm not sure how it does this). If you have a CSS file, you should modify the string returned by `renderFullPage` to include that.

```html
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <link rel="stylesheet" href="/static/css/index.css" />
</head>
```

Also, as an aside, you can tag code blocks as `js`/`jsx` for prettier highlighting

```
```jsx
// your code here
\``` (ignore the leading slash)
```

**Comment by mparker11** [comment]
It's compiling to CSS but I just realized there is no bundled CSS. I will take a look at what you mentioned. Thank you for your help. If I can't get anywhere, I will see about getting you a repo. But I'm trying not to bother you much :-)

**Comment by mparker11** [comment]
I finally found a way to do it. Someone was gracious enough to document how to do SSR in Create React App and once I replaced `<App />` (their code) with Curi's Provider code, I was in business. Here's the link to the project: https://github.com/kriasoft/react-app

Thanks for your help!
