### ISSUE TITLE
Server side rendering child routes not working

### ISSUE THREAD

**Issue by mparker11** [pshrmn/curi#45]
Trying not to bother you again but I'm trying to understand this issue I've run into.

I'm doing server-side-rendering and it's working well. But now I'm trying to render a child route and it's not loading correctly. Here's the scenario:

1. Load Home page ("")
2. Click to page two - child route ("posts/:post")

This works. However, if I refresh the child route ("posts/:post"), then only the elements load but not the styles. In my server file, I have (simplified)
```
const app = express();
app.use(express.static(path.join(__dirname, '/public')));

app.get('*', (req, res) => {
    const history = InMemory({ locations: [req.url] });
    const router = curi(history, routes);
    
    router.respond(() => {
        const pageMarkup = ReactDOMServer.renderToString(
            <CuriProvider router={ router }>
                {({ response }) => {
                    return <App response={ response } />;
                }}
            </CuriProvider>
        );
        
        res.send(`<html><head></head><body>${ pageMarkup }</body></html>`);
    });
});
```

I suspect it has something to do with the routes, which is why I'm writing the issue. Has anyone run into this? 

*Keep in mind that the parents routes are working just fine.

Thanks!

**Comment by pshrmn** [comment]
If I understand what you're saying, when you render a regular route, the generated HTML includes both the body and your styles, but when you render a nested route it is only rendering the body? Can you share the HTML output for both routes?

**Comment by mparker11** [comment]
You're correct. 
I linked to the html output files. Turns out, they are the same, although, there is no explicit link for the styles. So that leads me to believe that maybe this could be an explicit issue with the dev server.

[On Route Change](https://www.dropbox.com/s/il998mdnobirble/no_refresh.txt?dl=0)
[When Refreshing the Page](https://www.dropbox.com/s/806oipilkn81fg7/refresh.txt?dl=0)

The only difference I noticed is that the console is complaining about the bundle on refresh.
![shot_180404_201627](https://user-images.githubusercontent.com/825507/38345680-3c1d7efc-3845-11e8-81c7-3af059ad9131.jpg)

**Comment by mparker11** [comment]
After digging a little more into the webpackDevServer code, I am almost certain it's how it's configured. Any help into fixing it would be great, but I'm not sure it's the router's problem.

**Comment by pshrmn** [comment]
Ah, I see the issue. You are using a relative path in your request for `static/js/bundle.js`. When you request a nested route, this ends up getting missed by the static file handler (it is looking for `/nested/static/js/bundle.js` instead of `/static/js/bundle.js`). This should work:
```html
<script src="/static/js/bundle.js"></script>
```

**Comment by pshrmn** [comment]
This is a common issue people run into with SSR (I added it to React Router's FAQ because of how often it came up).

**Comment by mparker11** [comment]
You are a genius, it works! Thanks so much! This SSR thing is so crazy. Closing out and hopefully this will help another million SSR soldiers 😸
