### ISSUE TITLE
Navigation while response resolves can lead to unexpected history

### ISSUE THREAD

**Issue by pshrmn** [pshrmn/curi#5]
Currently, if the user clicks a link, then while the response for the new location is still resolving, clicks another link, the history array will include both locations.

```js
// current behavior
history = ['/start']
// user clicks link to '/next'
history = ['/start', '/next']
// '/next' response still resolving and user clicks link to '/finally'
history = ['/start', '/next', '/finally']
```
With non-SPAs, clicking another link while the browser is loading a new location results in the new location being replaced.
```js
// non-SPA behavior
history = ['/start']
// user clicks link to '/next'
history = ['/start', '/next']
// '/next' response still resolving and user clicks link to '/finally'
history = ['/start', '/finally']
```

This is only a problem for navigation that happens prior to a response resolving (which should trigger a re-render). Once a response has resolved, this is not an issue. 

Replacing the location would be ideal, but is not possible with the current Curi/Hickory implementations. There are a couple possible approaches to getting this working.

#### 1. Don't call `history.(push|replace)State` until a response has resolved.

This would require tighter integration between Curi and Hickory. Hickory would either have to have some special subscriber that is called prior to emitting (i.e. give Curi the location object, but don't emit until Curi has resolved a response) or emit a function that can be used to update the browser's history.

The biggest issue with this is that using the browser's buttons updates the browser's history outside of our control. There would either have to be behavior to "undo" and "redo" pop events or treat this type of navigation differently.

#### 2. Let history know that a location is not "final" until a response has resolved

If a Hickory history instance can know whether or not the last location has resolved, it can change its behavior for new navigation. For example, while resolving, any `push` calls will result in `window.history.replaceState` calls. This will result in the non-SPA behavior described above.

This seems like a better approach, but there are possible edge cases that can complicate this. For example, a `replace` call while a `push` is resolving` would leave an extra location in the browser's history unless we first undo the `PUSH`. `POP` navigation shouldn't be as much of an issue because those should be using cached data.

#### 3. Don't allow navigation while resolving a response.

Hickory could reject navigation (`navigate`/`push`/`replace` calls) while a response is resolving. This might be the most simple solution, but it is also not ideal.

-----

The second solution seems like the best bet. To start, replacing pushes should be good enough. While not correctly rolling back a replace is annoying, a lot of sites already don't allow replace anchor clicks to the same location. Eventually, if necessary, a transaction system could be implemented to roll back navigation.

**Comment by pshrmn** [comment]
Fixed by https://github.com/pshrmn/curi/commit/baee6de2e094cf81f2abb6a96a52fb275b293945, which takes advantage of Hickory now using a "response handler" instead of a subscriber model. Once the matched route's `preload` and `load` functions have resolved, Curi will "finish" the navigation. If any navigation happens prior to this, then the original navigation will be cancelled.

**Comment by bboydflo** [comment]
I am not user this has anything to do with the above, but I noticed something in one of codesandbox demo (the one with blocking navigation for react). when the form is half filled and the user clicks on browser back,  `curi` will prevent rendering the previous component, but now the url and the current page are not in sync.

I expect that curi should navigate back to the previous route if blocking was called, and only after confirm to actually go back.

**Comment by pshrmn** [comment]
@bboydflo CodeSandbox has a bug in its history implementation. I just ran the test locally and it worked as expected.

I was somewhat aware of this bug because it was also brought up in an issue with React Router. If I find the time, I might take a look at CodeSandbox's history code to see if I can identify where the bug is. For now, I should probably just add a note to the demos that mentions that they don't work as expected because of the bug.
