### ISSUE TITLE
Multiple Optional Parameters

### ISSUE THREAD

**Issue by mparker11** [pshrmn/curi#72]
Back again. I love the update to the routes. 

How do we add multiple optional parameters to a path in the routes? I couldn't find it in the docs.

Thanks!

**Comment by pshrmn** [comment]
Do you mean something like this `:one/:two?/:three?` to match `/hello`, `/hello/world`, and `/hello/world/star`?

All of Curi's path matching functionality comes from [`path-to-regexp`](https://github.com/pillarjs/path-to-regexp), so the docs there are the best resource, but I might expand the Curi docs a bit on the functionality.

Additionally, I wrote this little app for testing React Router routes, which can be useful here too https://pshrmn.github.io/route-tester. Maybe I'll port it to Curi as well.

**Comment by mparker11** [comment]
Yeah I pretty much mean the first example, `:one/:two?/:three?`. Thanks for linking to the package for regex. I'll take a look there.

**Comment by pshrmn** [comment]
Did you figure out what you were looking for @mparker11?

**Comment by mparker11** [comment]
Yep. Thanks again!

**Comment by nalexeric** [comment]
Hi @pshrmn! 
Is it possible that an optional parameter doesn't work as expected if it's the first part of a path? 
For example, the path `:lang?/about/:id` is only matched for urls like `/en/about/1`; if I'm trying to access the route without the language parameter, I get the 404.

Using the tool provided above, I can get a match for `/:lang?/about/:id` for both `/en/about/1` and `/about/1`.  I've also tried with exact and strict set to true and I still got a match. 

Is there anything I'm missing? I'm trying to have a routes config where each route is having that optional language parameter. Should I be trying a different approach to solve this? 

Thanks!

**Comment by pshrmn** [comment]
@nalexeric fixing in #100; will be released shortly.

`path-to-regexp` doesn't like matching when the initial segment is optional and has no leading slash (`/:lang?/about/:id` is fine, `:lang?/about/:id` is not). It is a bit strange since it will compile the path just fine, but it is faster for me to change Curi's implementation than to determine if something should be changed on `path-to-regexp`'s end.

**Comment by pshrmn** [comment]
And it is released; please let me know if you have any further issues.

**Comment by nalexeric** [comment]
Yes, #100 fixed my issue.
Thank you for your help and for this amazing router!
